### ISSUE TITLE
Bearing image of puck-2d is very sluggish

### ISSUE THREAD

**Issue by georgbachmann** [mapbox/mapbox-maps-ios#1230]
## Environment

- Xcode version: 13.3
- iOS version: 15.4.1
- Devices affected: All
- Maps SDK Version: 10.4.1

## Observed behavior and steps to reproduce

```
        mapView.location.options.puckType = .puck2D(.init(topImage: nil,
                                                          bearingImage: .init(named: "UserLocation"),
                                                          shadowImage: nil)
```

If you use a pick-type of 2D an also set a bearing image, that will rotate when the user rotates his phone. This in general is very good.
The problem though is that it is very sluggish. So it seems like it animates (?) to the users bearing with a quite long duration. Compared to the animation there is in the stocks iOS maps app, it is super slow.

## Expected behavior

The bearing image change much snappier. Maybe even without animation?

**Comment by nryrk** [comment]
*Sub*. I have exactly the same issue and would appreciate it if that could be fixed in the next version ☺️

**Comment by skienzl** [comment]
Any news on this one? I am having the same issue

**Comment by georgbachmann** [comment]
@ZiZasaurus may I also ask about that issue here? I think it's something that Android had as well but is already fixed there?!?

**Comment by georgbachmann** [comment]
@ZiZasaurus any update on this issue?

**Comment by ZiZasaurus** [comment]
@georgbachmann, this behavior exists on android as well. I have brought it to the team and we will investigate the root cause.

**Comment by bpepper88** [comment]
Any update on this ? 
Using version 11.6.0 of com.mapbox.maps:android and com.mapbox.extension:maps-compose. Issue still present.

**Comment by aleksproger** [comment]
@bpepper88 if you see this on Android may you please instead create an issue in Android repository
