### ISSUE TITLE
ViewAnnotation disappearing mid-screen when panning up the map. 

### ISSUE THREAD

**Issue by thib4ult** [mapbox/mapbox-maps-ios#2057]
## Environment

- Xcode version: 15.0.1
- iOS version: All
- Devices affected: All
- Maps SDK Version: V11.0 and 10.16

## Observed behavior and steps to reproduce

The view annotation is disappearing about mid-screen when scrolling up on the map IF the map has a high pitch (about 50 in my case) AND IF the zoom is high (about 10 in my case)

I uploaded a video from your test app that has the issue also. 

https://github.com/mapbox/mapbox-maps-ios/assets/2362691/3524f655-7a16-4abb-8132-d7805dc9ceae

## Expected behavior

The annotations should disappear only when they go off screen. 

## Notes / preliminary analysis

Lower the pitch value is, the more you can scroll up until the annotation disappear.

**Comment by persidskiy** [comment]
@thib4ult Thanks you for the feedback. 

We aware of some placement issues with pitched camera. It should be fixed in the upcoming v11.0.0-rc.2 version. Can you try to use the Maps version from the `main` branch? Will it be better for your use-case?

tip: you can turn on debug options to see bounds of the elements on the map and see if they collide. Note: when view annotation goes beyond camera padding, it hides.
```
mapView.debugOptions = [.camera, .padding, .collision]
```

**Comment by thib4ult** [comment]
@persidskiy Thank you for your comment and thanks for releasing v11.0.0-rc.2. Everything works well with that new release. 

Thanks again.

**Comment by baleboy** [comment]
Thanks for the follow-up!

**Comment by MichaelDanielTom** [comment]
Still experiencing this, and while it does seem to appear more with pitched camera, it still seems to happen without a pitch in `v11.0.0-rc.2` when panning and zooming with certain annotations.

[Related vid that's still happening for me in `v11.0.0-rc.2` (although vid was on `v11.0.0-rc.2`).](https://github.com/rnmapbox/maps/issues/3139#issuecomment-1802588863)

**Comment by MichaelDanielTom** [comment]
It would appear that setting `allowOverlapWithPuck` to true fixes my issue!
