### ISSUE TITLE
EXC_BAD_ACCESS when GeoJSONSource.cluster is set to true

### ISSUE THREAD

**Issue by a-h-mzd** [mapbox/mapbox-maps-ios#2315]
## Environment

- Xcode version: 16.3
- iOS version: 18.4
- Devices affected: All iPhone devices
- Maps SDK Version: 11.10.* ~ 11.11.0

## Observed behavior and steps to reproduce

When updating a `GeoJSONSource` each frame using `CADisplayLink`, the map crashes only when the `cluster` property is set to true. Otherwise, it works fine.

## Expected behavior

The map must not crash when clustering is enabled.

## Notes / preliminary analysis

The error thrown is bad memory access (EXC_BAD_ACCESS)

**Comment by OdNairy** [comment]
@a-h-mzd could you provide a sample project? How easy is it to reproduce the issue in your case?

**Comment by a-h-mzd** [comment]
@OdNairy it is pretty easy to reproduce as the crash happens always. I will provide a sample project as soon as possible.

**Comment by a-h-mzd** [comment]
**Steps to reproduce:**

1. Navigate to the sample VC
2. Put the app into background
3. Bring the app to foreground
4. Checkout the crash

There are other ways to reproduce the issue but this one is fast and reliable. My guess is they all originate from the same faulty code. Note that following the same instructions while `GeoJSONSource.cluster` is set to **_false_** will result in no errors.

_any suggestions on how to improve the sample code is also appreciated!_

<details open>
  <summary>Sample ViewController</summary>

```swift
import UIKit
import Combine
import SDWebImage
import MapboxMaps

class TVC: SharedUIViewController {
    
    private var cancellables: Set<AnyCancellable> = []
    
    private let mapView: MapView = .init(frame: .zero, mapInitOptions: .init())
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        hidesBottomBarWhenPushed = true
    }
    
    @MainActor required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        mapView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(mapView)
        mapView.pinInSuperview()
        
        mapView.mapboxMap.setCamera(to: .init(center: .init(latitude: 52.5140293, longitude: 13.3553706), zoom: 12))
        mapView.mapboxMap.onStyleImageMissing
            .observe { [weak self] event in self?.setupImage(url: event.imageId) }.store(in: &cancellables)
        
        displayLink = CADisplayLink(target: DisplayLinkProxy(target: self), selector: #selector(DisplayLinkProxy.update))
        displayLink?.add(to: .main, forMode: .common)
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        bounds = mapView.mapboxMap.coordinateBounds(for: mapView.bounds)
        for _ in 0..<10 { addPoint() }
        
        timer = Timer.scheduledTimer(withTimeInterval: 1, repeats: true) { [weak self] _ in self?.updatePoints() }
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(true, animated: animated)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        navigationController?.setNavigationBarHidden(false, animated: animated)
    }
    
    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)
        timer?.invalidate()
        displayLink?.invalidate()
    }
    
    private func setupImage(url: String) {
        
        var uri = url
        if uri.contains("!") {
            uri = "https://picsum.photos/300"
        }
        
        SDWebImageManager.shared.loadImage(with: .init(string: uri), progress: nil) { [weak self] image, _, _, _, _, _ in
            guard let mapboxMap = self?.mapView.mapboxMap else { return }
            
            let imageView: UIImageView = .init(frame: .init(origin: .zero, size: .init(size: 60)))
            imageView.contentMode = .scaleAspectFill
            imageView.image = image
            imageView.layer.cornerRadius = 30
            imageView.layer.masksToBounds = true
            try! mapboxMap.addImage(imageView.imageRepresentation!, id: url)
        }
    }
    
    private static let sourceId: String = "test-source"
    private static let layerId: String = "test-layer"
    private static let clusterLayerId: String = "test-cluster-layer"
    private var timer: Timer?
    private var displayLink: CADisplayLink?
    private var latestInfoUpdates: [String : TestInfo] = [:]
    private func addLayer(mapboxMap: MapboxMap) throws {
        
        if !mapboxMap.sourceExists(withId: Self.sourceId) {
            var geoJSONSource = GeoJSONSource(id: Self.sourceId)
            geoJSONSource.data = .featureCollection(.init(features: []))
            geoJSONSource.cluster = true
            geoJSONSource.clusterRadius = 70
            geoJSONSource.clusterProperties = [
                "cluster-avatar": Exp(.concat) {
                    Exp(.concat) {
                        Exp(.get) { "avatar" }
                        Exp(.string) { "!" }
                    }
                }
            ]
            try mapboxMap.addSource(geoJSONSource)
        }
        
        if !mapboxMap.layerExists(withId: Self.layerId) {
            var layer: SymbolLayer = .init(id: Self.layerId, source: Self.sourceId)
            layer.iconAllowOverlap = .constant(true)
            layer.iconImage = .expression(Exp(.get) { "avatar" })
            layer.filter = Exp(.not, Exp(.has, "point_count"))
            try mapboxMap.addLayer(layer)
        }
        
        if !mapboxMap.layerExists(withId: Self.clusterLayerId) {
            var layer: SymbolLayer = .init(id: Self.clusterLayerId, source: Self.sourceId)
            layer.iconAllowOverlap = .constant(true)
            layer.iconImage = .expression(Exp(.get) { "cluster-avatar" })
            layer.filter = Exp(.has, "point_count")
            try mapboxMap.addLayer(layer)
        }
    }
    fileprivate func updateSourceInfo() {
        guard let mapboxMap = mapView.mapboxMap else { return }
        
        try! addLayer(mapboxMap: mapboxMap)
        
        let avatar = "https://picsum.photos/200"
        
        let now = CACurrentMediaTime()
        var featuresToUpdate: [Feature] = []
        let infoUpdates = latestInfoUpdates
        for (id, infoUpdate) in infoUpdates {
            if let start = infoUpdate.animationStartTime, let dest = infoUpdate.destinationCoord {
                let t = min((now - start) / infoUpdate.animationDuration, 1.0)
                
                let newLat = infoUpdate.originCoord.latitude + t * (dest.latitude - infoUpdate.originCoord.latitude)
                let newLon = infoUpdate.originCoord.longitude + t * (dest.longitude - infoUpdate.originCoord.longitude)
                let newCoord = CLLocationCoordinate2D(latitude: newLat, longitude: newLon)
                
                var feature = Feature(geometry: Point(newCoord))
                feature.identifier = .string(id)
                feature.properties = [ "avatar": .string(avatar) ]
                featuresToUpdate.append(feature)
                
                var infoUpdate = infoUpdate
                if t >= 1.0 {
                    infoUpdate.currentCoord = dest
                    infoUpdate.originCoord = dest
                    infoUpdate.animationStartTime = nil
                } else {
                    infoUpdate.currentCoord = newCoord
                }
                latestInfoUpdates[id] = infoUpdate
            } else {
                // No animation in progress for this user, use its currentCoord
                var feature = Feature(geometry: Point(infoUpdate.currentCoord))
                feature.identifier = .string(id)
                feature.properties = [ "avatar": .string(avatar) ]
                featuresToUpdate.append(feature)
            }
        }
        let geoJSONSourceData: GeoJSONSourceData = .featureCollection(.init(features: featuresToUpdate))
        mapboxMap.updateGeoJSONSource(withId: Self.sourceId, data: geoJSONSourceData)
    }
    
    private lazy var bounds: CoordinateBounds? = nil
    private func addPoint() {
        guard let bounds else { return }
        
        let lon = Double.random(in: bounds.west...bounds.east)
        let lat = Double.random(in: bounds.south...bounds.north)
        
        let id = UUID().uuidString
        
        latestInfoUpdates[id] = .init(
            originCoord: .init(latitude: lat, longitude: lon),
            currentCoord: .init(latitude: lat, longitude: lon),
            timestamp: .now
        )
    }
    private func updatePoints() {
        guard let bounds else { return }
        
        for (id, info) in latestInfoUpdates {
            let lon = Double.random(in: bounds.west...bounds.east)
            let lat = Double.random(in: bounds.south...bounds.north)
            
            let currentCoord = info.currentCoord
            latestInfoUpdates[id] = .init(
                originCoord: currentCoord,
                currentCoord: currentCoord,
                destinationCoord: .init(latitude: lat, longitude: lon),
                animationStartTime: CACurrentMediaTime(),
                timestamp: .now
            )
        }
    }
}

private class DisplayLinkProxy {
    weak var target: TVC?
    init(target: TVC) { self.target = target }
    @objc func update() { target?.updateSourceInfo() }
}

private struct TestInfo {
    var originCoord: CLLocationCoordinate2D
    var currentCoord: CLLocationCoordinate2D
    var destinationCoord: CLLocationCoordinate2D?
    var animationStartTime: CFTimeInterval?
    let animationDuration: TimeInterval = 1
    let timestamp: Date
}

extension UIView {
    var imageRepresentation: UIImage? {
        let size = CGSize(width: frame.size.width, height: frame.size.height)
        UIGraphicsBeginImageContextWithOptions(size, false, (window?.screen ?? UIScreen.main).scale)
        guard let currentContext = UIGraphicsGetCurrentContext() else { return nil }
        layer.render(in: currentContext)
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        
        // Check the transform property to see if the view was flipped.
        // If it was then we need to apply a flip transform here as well since layer.render() ignores the view's
        // transform when it is rendered
        let isFlipped = transform.a == -1
        return isFlipped ? image?.withHorizontallyFlippedOrientation() : image
    }
}
```
</details>

**Comment by a-h-mzd** [comment]
@OdNairy I found out that even when not using **DisplayLink**, the app still crashes — it just takes more time for the crash to surface.

**Comment by OdNairy** [comment]
@a-h-mzd could you check the latest `11.12.0` release?
Now as you provided a sample code I could see that it might be related to the crash we've addressed in the 11.12.0

See also:
- https://github.com/mapbox/mapbox-maps-ios/issues/2311
- https://github.com/mapbox/mapbox-maps-ios/issues/2323

In case it doesn't help I would ask you to provide a sample project as a separate xcodeproj so we could run it as-is without an extra modifications needed.

**Comment by a-h-mzd** [comment]
@OdNairy thanks for the info. I will check and update the ticket accordingly.

**Comment by a-h-mzd** [comment]
We're experiencing this crash on the latest version 👍🏼 @OdNairy

**Comment by a-h-mzd** [comment]
@OdNairy we're still experiencing crashes but I'm not sure if it is relevant to the previous crashes.
```console
0   libsystem_malloc.dylib        	0x00000001a474e020 _xzm_xzone_malloc_tiny_outlined + 724 (xzone_malloc.c:1719)
1   MapboxCommon                  	0x0000000103c64598 0x103b64000 + 1050008
2   MapboxCommon                  	0x0000000103b7a198 0x103b64000 + 90520
3   MapboxCommon                  	0x0000000103b8f964 0x103b64000 + 178532
4   MapboxCommon                  	0x0000000103bbde80 0x103b64000 + 368256
5   MapboxCommon                  	0x0000000103bb8f4c 0x103b64000 + 347980
6   MapboxCommon                  	0x0000000103b80038 0x103b64000 + 114744
7   MapboxCommon                  	0x0000000103e25844 mapbox::sqlite::Query::_run() + 44
8   MapboxCommon                  	0x0000000103d0db40 0x103b64000 + 1743680
9   MapboxCommon                  	0x0000000103e9a1f8 0x103b64000 + 3367416
10  MapboxCommon                  	0x0000000103e9b414 0x103b64000 + 3372052
11  MapboxCommon                  	0x0000000103f05bf8 0x103b64000 + 3808248
12  MapboxCommon                  	0x0000000103f0c22c 0x103b64000 + 3834412
13  MapboxCommon                  	0x0000000103e95b3c 0x103b64000 + 3349308
14  MapboxCommon                  	0x0000000103d1434c 0x103b64000 + 1770316
15  libsystem_pthread.dylib       	0x000000021e647344 _pthread_start + 136 (pthread.c:931)
16  libsystem_pthread.dylib       	0x000000021e644ab8 thread_start + 8
```
